services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: toymarc-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - toymarc-network
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: toymarc-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: toymarc
      MYSQL_ROOT_PASSWORD: toymarc_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - toymarc-network

networks:
  toymarc-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
