services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: toymarc-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - /var/www/html/vendor # vendor フォルダは除外（コンテナ内で生成されたものを使用）
      - /var/www/html/node_modules # node_modules フォルダは除外（コンテナ内で生成されたものを使用）
      - dmarc_reports:/var/www/html/storage/app/dmarc_reports
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=toymarc
      - DB_USERNAME=root
      - DB_PASSWORD=toymarc_password
      - APP_LOCALE=ja
      - APP_FALLBACK_LOCALE=en
      - APP_TIMEZONE=Asia/Tokyo
    networks:
      - toymarc-network
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: toymarc-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: toymarc
      MYSQL_ROOT_PASSWORD: toymarc_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - toymarc-network

networks:
  toymarc-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  dmarc_reports:
    driver: local
