services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: laravel-frankenphp-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - laravel-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel_password

  db:
    image: mysql:8.0
    container_name: laravel-frankenphp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
